### PR TITLE
expose reader and js functions globally

### PR DESCRIPTION
**Pull request by JeremiGendron**
#90 I probably won't work on this very much in the coming days. I am therefore sharing my findings in hopes that it may help someone else.

### CODE REVIEW

**Comment by jeluard** [comment]
That's a great start! Do you have a simple sample of how it would be used in a new node project?

**Comment by jeluard** [comment]
Yes it is!

> You can make use of webpack, gulp or a similar library to make it browser compatible.

Which one do you think is the best option?

**Comment by JeremiGendron** [comment]
I remember using browserify and it being very simple.

**Comment by JeremiGendron** [comment]
`Caused by: java.io.FileNotFoundException: Could not locate pluto/storage/http__init.class or pluto/storage/http.clj on classpath.` when compiling with `lein cljsbuild once nodejs` with `:main pluto.js` and `:main pluto.reader` both.

**Comment by JeremiGendron** [comment]
closed for #116 , which now includes a cleaner structure and both nodejs/browser Proofs of Concept.

**Pull request closed without merging**
